apptainer/apptainer-admindocs

- README.md
Update the README for the Apptainer project.
> Update README for Apptainer

- .github/workflows/pull_request.yml
This is a cherry-pick of a commit from apptainer/apptainer-userdocs#42
> Reintroduce separate rst lint step

- admin_quickstart.rst
- appendix.rst
- configfiles.rst
- index.rst
- installation.rst
- replacements.py
- security.rst
- user_namespace.rst
> Change {Singularity} replacement to {Project} and set it to Apptainer

- configfiles.rst
- installation.rst
- security.rst
- user_namespace.rst
> Remove references to older Singularity versions

- admin_quickstart.rst
- conf.py
- installation.rst
- pygments_singularity.py
- replacements.py
Signed-off-by: Pedro Alves Batista <pedro.pesquisapb@gmail.com>
Replaces any reference of HPCng to Apptainer.
* Fixes:
#7
> Update references from HPCng to Apptainer 

- admin_quickstart.rst
- installation.rst
Signed-off-by: Pedro Alves Batista <pedro.pesquisapb@gmail.com>
Removes any reference to old versions of Singularity.
* Fixes:
#15
> Remove references to old Singularity versions 

- .gitignore
Signed-off-by: Ian Kaneshiro <iankane@umich.edu>
> Ignore vscode configurations

- configfiles.rst
Signed-off-by: Ian Kaneshiro <iankane@umich.edu>
Related to https://github.com/apptainer/apptainer-userdocs/pull/63
> DMTCP configuration file docs

- admin_quickstart.rst
- configfiles.rst
- installation.rst
Signed-off-by: Ian Kaneshiro <iankane@umich.edu>
Sibling PR: https://github.com/apptainer/apptainer-userdocs/pull/66
> Update Library API related docs

- index.rst
- singularity_migration.rst
Fixes #14 
Sibling PR: https://github.com/apptainer/apptainer-userdocs/pull/68
> Singularity Migration Docs

- installation.rst
- security.rst
Tweaks from proof reading the docs
> installation.rst

- configfiles.rst
Fixes formatting and remove label added in #34
> Fix the section on restoring previous library behavior

- replacements.py
Set the branch in replacments.py to 1.0
> Update branch in replacements.py

- user_namespace.rst
This cherry-picks #41 to the 1.0 branch
> Update user_namespace.rst, from sylabs 41(1.0)

- configfiles.rst
- sylabs/singularity-admindocs#54
which fixed
- sylabs/singularity-admindocs#47
The original PR description was:
> * New `singularity.conf` options.
> * New cgroups functionality (unpriv, unified v2)
> Update configfiles.rst, from sylabs 54

- installation.rst
Fix the bash completion path.
- Fixes #43
> Update bash completion path

- admin_quickstart.rst
- configfiles.rst
- installation.rst
- replacements.py
- user_namespace.rst
This has a lot more updates for apptainer-1.1 changes.  It goes along with apptainer/apptainer-userdocs#111.  I think it covers most of the changes needed for admindocs, but I plan to do another pass later to see if anything was missed.
> More updates for apptainer-1.1

- replacements.py
Just update the version number to the latest release candidate.
> Update for 1.1.0-rc.2

- replacements.py
This updates the replacement.py tags to 1.1.0-rc.3
> Update to 1.1.0-rc.3

- replacements.py
This cherry-picks #59 to the 1.1 branch.
> Update install version (1.1)

- replacements.py
This cherry-picks #61 to the branch it was supposed to be on.
> Update branch variables for 1.1

- conf.py
> Update version to 1.1

- replacements.py
> Update for 1.1.2

- replacements.py
This cherry-picks #67 to the 1.1 branch
> update for 1.1.2 (1.1)

- installation.rst
This cherry-picks #70 to the 1.1 branch.
> Make clear that setuid is still an option (1.1)

- replacements.py
This updates the version number to 1.1.3
> Update for 1.1.3

- replacements.py
This cherry-picks #75 to the 1.1 branch
> Update for 1.1.3 (1.1)

- user_namespace.rst
- Fixes apptainer/apptainer#854
> Fix network namespace setting typos

- user_namespace.rst
This cherry-picks #77 into the 1.1 branch
> Fix network namespace setting typos (1.1)

- replacements.py
- Analogous to apptainer/apptainer-userdocs#140
> Fix repobranch to be release-1.1

- .github/workflows/publish.yml
> Add symlink

- .github/workflows/pull_request.yml
- _templates/layout.html
- sylabs/singularity-admindocs#62
The original PR description was:
> add old version notice
> add 1.0 old version notice, from sylabs 62

- replacements.py
> update to 1.1.4

- installation.rst
This cherry-picks #84 to the 1.1 branch.
> Add usage of install-unprivileged.sh (1.1)

- configfiles.rst
- singularity_migration.rst
This cherry-picks #88 to the 1.1 branch.
> Describe automated rpm import of singularity config (1.1)

- replacements.py
> Update to 1.1.5

- replacements.py
This cherry-picks #92 to the 1.1 branch.
> Update to 1.1.5 (1.1)

- installation.rst
Signed-off-by: Yoshiaki Senda <yoshiaki@live.it>
> Update Installation procedure for Ubuntu

- user_namespace.rst
This cherry-picks #97 to the 1.1 branch.
> Clarify the availability of non-subuid mapped fakeroot (1.1)

- installation.rst
Signed-off-by: Yoshiaki Senda yoshiaki@live.it
> Separating installation procedures for Debian and Ubuntu

- installation.rst
Signed-off-by: Yoshiaki Senda <yoshiaki@live.it>
> PPA supports all current Ubuntu releases except 18.04

- installation.rst
cherry-pick #100
* PPA supports all current Ubuntu releases except 18.04
Signed-off-by: Yoshiaki Senda <yoshiaki@live.it>
* add "except 18.04"
Signed-off-by: Yoshiaki Senda <yoshiaki@live.it>
> PPA supports all current Ubuntu releases except 18.04 (#100)

- .github/workflows/publish.yml
admindocs equivalent of apptainer/apptainer-userdocs#158
> Fix bullet list rendering

- .github/workflows/publish.yml
> Finish fixing bullet rendering

- .github/workflows/publish.yml
This cherry-picks #102 and #103 into the 1.1 branch.
> Fix bullet list rendering (1.1)

- replacements.py
> Update for 1.1.6

- replacements.py
This cherry-picks #161 to the 1.1 branch
> update for 1.1.6 (1.1)

- LICENSE
This pulls in sylabs part of PR
- sylabs/singularity-admindocs#85
> Update copyright years, from sylabs 85

- installation.rst
- sylabs/singularity-admindocs#83
which fixed
- sylabs/singularity-admindocs#75
> document PanFS limitations, from sylabs 83

- conf.py
- sylabs/singularity-admindocs#90
> Missed main in conf.py, from sylabs 90

- configfiles.rst
- replacements.py
This cherry-picks #112 and #113 to the 1.1 branch.
> Merge 1.1.8 changes (1.1)

- configfiles.rst
- replacements.py
- sylabs/singularity-admindocs#91
> Install / config changes as of 3.11.3, from sylabs 91

- replacements.py
> Update to 1.1.9

- installation.rst
Remove references to Ubuntu 18.04.
> Remove ubuntu 18.04

- replacements.py
Update main branch for 1.2.0-rc.1
> Update for 1.2.0-rc.1

- conf.py
Missed when updating replacements.py
> Set 1.2 in the conf.py version too

- replacements.py
Update replacements for the 1.2.2 release.
> Update for 1.2.2

- replacements.py
This cherry-picks #125 to the 1.2 branch.
> Update for 1.2.2 (1.2)

- installation.rst
This cherry-picks #124 into the 1.2 branch
> Update installation file for homebrew (1.2)

- replacements.py
> Update for 1.2.3 (1.2)

- replacements.py
Cherry-pick #132 to the 1.2 branch
> Update to 1.2.4 (1.2)

- replacements.py
This is basically a no-op to re-publish to new website area.
> Kick off republish

- .github/workflows/publish.yml
This PR updates the workflow file to reflect a change in the directory structure for the new site.
> Update publish.yml for new site

- .github/workflows/publish.yml
Cherry-pick #137 into the 1.2 branch
> Fix workflow for new site (1.2)

- replacements.py
Cherry-pick #139 to the 1.2 branch
> Update for 1.2.5 (1.2)

- index.rst
- monitoring.rst
https://github.com/apptainer/apptainer/pull/1720
- Fixes #
> add new docs for 1.3.0 new features

- installation.rst
This fixes a subpart of #146 by importing/modifying
- sylabs/singularity-admindocs#120
which fixed
- sylabs/singularity-admindocs#103
> Document kernel vs fuse overlay circumstances, from sylabs120

- installation.rst
As a subpart of #146 this pulls in portions of
- sylabs/singularity-admindocs#117
which fixed
- sylabs/singularity-admindocs#115
The original PR description was
> Remove Vagrant cloud references.
> 
> Move docker image section down, and clarify relationship to the project.
> Update Windows instructions to WSL2

- configfiles.rst
As a subpart of #146, this pulls in part of
- sylabs/singularity-admindocs#136
and changes other parts pf the configuration documentation related to changes in apptainer-1.3.0.
> Update FUSE related and other config documentation, partly from sylabs136

- conf.py
- replacements.py
Make the 1.3 branch ready as a release branch.
> Update for 1.3 branch

- installation.rst
This answers some questions that have arisen about apptainer-1.3.
> List FUSE as a kernel requirement

- installation.rst
This cherry-picks #155 to the 1.3 branch.
> List FUSE as a kernel requirement (1.3)

- replacements.py
cherry-pick #157 to the 1.3 branch
> update to 1.3.1 (1.3)

- replacements.py
Cherry-pick of #163 into the 1.3 branch
> update to 1.3.3 (1.3)

- installation.rst
- user_namespace.rst
> remove el7 references (1.3)

- installation.rst
> Clarify when changing --localstatedir might be needed

- installation.rst
Cherry-pick #168 to the 1.3 branch.
> Clarify when changing --localstatedir might be needed (1.3)

- security.rst
Cherry-pick #172 to the 1.3 branch
> Correct the description of cgroup v2 delegation (1.3)

- installation.rst
> remove another el7 reference

- installation.rst
Cherry-pick #174 to the 1.3 branch
> remove another el7 reference (1.3)

- replacements.py
Cherry-pick #176 to the 1.3 branch
> Update to 1.3.4 (1.3)

- replacements.py
Cherry-pick #180 to the 1.3 branch
> update to 1.3.6 (1.3)

- installation.rst
Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
Previous links were to non existent examples directory causing 404 errors
Updated links to the correct templates directory and the relevant yaml files.
- Fixes # [182](https://github.com/apptainer/apptainer-admindocs/issues/182)
> fix: paths to apptainer and default templates

- replacements.py
> Update to 1.4.0-rc.1

- .github/workflows/publish.yml
Just like apptainer/apptainer-userdocs#309 and apptainer/apptainer-userdocs#311.
> update docutils version

- installation.rst
Add link to the Lima home page with documentation, and use the default config (VZ, 4 CPU, 4 GiB RAM).
Add some more text to explain what it actually is, similar to the introduction about WSL2 on Windows.
Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
- Fixes #
> Update the instructions for Lima Apptainer

- user_namespace.rst
- Fixes #apptainer/apptainer-userdocs#307
> update for libsubid support

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/default-issue-template.md
This restores the issue template functionality, analogous to apptainer/apptainer-userdocs#355
> Restore issue template

- .github/workflows/pull_request.yml
- Makefile
- copyreplace.py
Implements the same changes as in https://github.com/apptainer/apptainer-userdocs/pull/351
- Follows https://github.com/apptainer/apptainer-userdocs/issues/350
> fix rst lint (sam as in apptainer-userdocs)

- configfiles.rst
- Fixes apptainer/apptainer-userdocs#329
> Add section on registries.conf mirrors

- configfiles.rst
- installation.rst
- user_namespace.rst
Cherry-pick #207 to the 1.4 branch
> Add section on running inside docker (1.4)
