apptainer/apptainer-admindocs

configfiles.rst
installation.rst
replacements.py

Signed-off-by: Pedro Alves Batista <pedro.pesquisapb@gmail.com>
Removes environmental variables from SINGULARITY to {ENVPREFIX}.
* Fixes:
#12

Replaces env vars from SINGULARITY to {ENVPREFIX} 

---

.github/workflows/pull_request.yml
copyreplace.py

This brings in replacements before running rstcheck, cherry-picking one of the commits from apptainer/apptainer-userdocs#56.

Apply replacements to rstcheck

---

user_namespace.rst

- sylabs/singularity-admindocs#41
The original PR description was:
> setup != set up

Update user_namespace.rst, from sylabs 41

---

security.rst

- sylabs/singularity-admindocs#53
which fixed
- sylabs/singularity-admindocs#45

Add unpriv cgroups notes to security.rst, from sylabs 53

---

.github/workflows/pull_request.yml

This is a cherry-pick from apptainer/apptainer-userdocs#103.  It fixes these errors seen in the rstcheck CI test here:
```
Error: No such option: --ignore-language (Possible options: --ignore-languages, --ignore-messages, --ignore-roles)
```
```
Error: No such option: --report Did you mean --report-level?
```

fix rstcheck usage

---

installation.rst

Just some minor fixes I found following the tutorial:
- define minimum Go version to 1.16.12 (as stated in `mconfig`)
- fix the missing version in folder name after unpacking from tar

Add minor missing versions

---

admin_quickstart.rst
security.rst
user_namespace.rst

This makes the user namespaces+fakeroot and security pages consistent with apptainer-1.1.  Goes along with corresponding PR apptainer/apptainer-userdocs#110.

Update user namespaces, fakeroot & security for apptainer-1.1

---

replacements.py

This undoes the changes from #61 which was mistakenly applied to the main branch.

Undo mistaken branch variable changes

---

installation.rst
user_namespace.rst

In particular for unprivileged FUSE mounts

Update kernel requirements

---

installation.rst

This adds a line to the System Requirements section that clarifies that setuid is still an option by referring to below instructions.

Make clear that setuid is still an option

---

installation.rst

I found that fake fakeroot mode also has similar restrictions for remote filesystems as the subuid mappings fakeroot.

Extend fakeroot restrictions on nfs/lustre/gpfs to include fake fakeroot

---

installation.rst

This cherry-picks #86 to the 1.1 branch.

Extend fakeroot restrictions on nfs/lustre/gpfs to include fake fakeroot (1.1)

---

installation.rst

This cherry-picks #89 to the 1.1 branch.

Add SUSE to the list of OSes supported by install-unprivileged.sh (1.1)

---

configfiles.rst
singularity_migration.rst

This updates the discussion of singularity migration to match apptainer/apptainer#969 which will go into apptainer-1.1.5.  This should be cherry-picked to the 1.1 branch after 1.1.5 is released.
It also updates the discussion of the default remote endpoint similarly to apptainer/apptainer-userdocs#150.

Describe automated rpm import of singularity config

---

configfiles.rst

- sylabs/singularity-admindocs#88
The original PR description was:
> * Mention proot, OCI functionality.
> * Tweak explanation of implications of unprivileged install / userns.
> * Highlight effect on security restrictions of unprivileged install.

Edits, from sylabs 88

---

configfiles.rst

- sylabs/singularity-admindocs#87
which fixed
- sylabs/singularity-admindocs#78

Update sessiondir max size comment, from sylabs 87

---

replacements.py

I had forgotten the `-1` on the github download version.

Fix github download version

---

installation.rst

This cherry-picks #130 to the 1.2 branch.

Mention installation of oldest EPEL by default (1.2)

---

installation.rst

The license changed with the 2.4.0 release
But it is still freely available as a tool.
Vagrant license changed from MPL to BSL
See: https://hashi.co/bsl-blog

Hashicorp Vagrant is no longer Open Source

---

README.md
installation.rst

The README has an incorrect link to the Apptainer CONTRIBUTING documentation, and the Vagrantfile example for running Apptainer on Mac has an outdated version of Fedora 36 Cloud that isn't available anymore. This PR corrects those links.
- See above

Fix for two 404 links

---

configfiles.rst

This fixes a subpart of #146 by importing a subset of
- sylabs/singularity-admindocs#95
The original PR description was
> Add clear warnings regarding the implications of unprivileged user namespace creation on container execution limits.

Add unpriv user namespace warnings, from sylabs95

---

installation.rst
user_namespace.rst

Make the kernel requirement descriptions match apptainer-1.3.0's usage.
- Continuation of apptainer/apptainer-userdocs#240

Updates for use of FUSE in suid mode

---

installation.rst

Fixes a bad use of macro introduced in #168.

Use the correct macro for lower case command

---

security.rst

By default only memory and pids are available to be limited by non-root users with cgroups v2.

Correct the description of cgroup v2 delegation

---

configfiles.rst

add uts|usr ns|ipc flags in apptainer.conf
- Fixes apptainer/apptainer-userdocs#317

add uts|usr ns|ipc flags in apptainer.conf

---

configfiles.rst

add --netns-path for admindocs
- Fixes https://github.com/apptainer/apptainer-userdocs/issues/315

add --netns-path for admindocs
